name: ui_library
description: Uplink UI Library.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: "2.10.4"

dependencies:
  dropdown_button2: ^1.4.0
  flutter:
    sdk: flutter
  golden_toolkit: ^0.13.0
  shared_preferences: ^2.0.13
  alchemist: ^0.3.2
  image_cropper: ^2.0.2
  image_picker: ^0.8.5+3
  screenshot: ^1.2.3
  permission_handler: ^9.2.0
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/placeholders/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/text/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/text/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/text/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/text/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/text/Poppins-Italic.ttf
          weight: 400

    - family: SpaceMono
      fonts:
        - asset: fonts/text/SpaceMono-Bold.ttf
          weight: 700
          
    - family: UIcons
      fonts:
        - asset: fonts/icon/UIcons.ttf
