name: ui_library
description: Uplink UI Library.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: "3.0.5"

dependencies:
  dropdown_button2: ^1.7.2
  flutter:
    sdk: flutter
  golden_toolkit: ^0.13.0
  shared_preferences: ^2.0.15
  alchemist: ^0.4.1
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  screenshot: ^1.2.3
  permission_handler: ^9.2.0
  image_gallery_saver: ^1.7.1
  qr_flutter: ^4.0.0
  intl: ^0.17.0
  html: ^0.15.0
  given_when_then_unit_test: ^0.1.0
  shouldly: ^0.5.0+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/placeholders/
    - images/networks_logo/
    - images/file_graph/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/text/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/text/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/text/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/text/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/text/Poppins-Italic.ttf
          weight: 400

    - family: SpaceMono
      fonts:
        - asset: fonts/text/SpaceMono-Bold.ttf
          weight: 700
          
    - family: UIcons
      fonts:
        - asset: fonts/icon/UIcons.ttf
