/// Flutter icons UIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UIcons
///      fonts:
///       - asset: fonts/UIcons.ttf
///
///
///
/// The icons was collected from Lucide Library
/// Copyright (c) 2020, Lucide Contributors

// ignore_for_file: constant_identifier_names

import 'u_icon_data.dart';

/// Class with all [UIconData] that can be used in the app already setted.
class UIcons {
  UIcons._();

  static const _kIconsFontFamily = 'UIcons';
  static const String? _kIconsFontPackage = null;

  static const UIconData about_icon = UIconData(0xe800,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData add_button = UIconData(0xe801,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData add_contact_member_icon = UIconData(0xe802,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData add_folder_icon = UIconData(0xe803,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData add_note_icon = UIconData(0xe804,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData back_arrow_button = UIconData(0xe805,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData call_icon = UIconData(0xe806,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData camera_icon = UIconData(0xe807,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData chatbar_gifs = UIconData(0xe808,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData chatbar_emojis = UIconData(0xe809,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData chatbar_send_button = UIconData(0xe80a,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData chatbar_stickers = UIconData(0xe80b,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData checkmark_icon = UIconData(0xe80c,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData close_button = UIconData(0xe80d,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData compose_message_button = UIconData(0xe80e,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData copy_clone_button = UIconData(0xe80f,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData end_call_icon = UIconData(0xe810,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData end_video_call_icon = UIconData(0xe811,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData favorite_button = UIconData(0xe812,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData file_icon = UIconData(0xe813,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData forward_arrow_button = UIconData(0xe814,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData friend_added_icon = UIconData(0xe815,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData grid_view = UIconData(0xe816,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData hamburger_menu = UIconData(0xe817,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData lefthand_navigation_drawer = UIconData(0xe818,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData link_button = UIconData(0xe819,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData list_view = UIconData(0xe81a,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData location_icon = UIconData(0xe81b,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData menu_bar_contacts = UIconData(0xe81c,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData menu_bar_files = UIconData(0xe81d,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData menu_bar_home = UIconData(0xe81e,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData menu_bar_notifications = UIconData(0xe81f,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData message_icon = UIconData(0xe820,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData multiple_accounts_icon = UIconData(0xe821,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData mute_icon = UIconData(0xe822,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData pin_entry_backspace_button = UIconData(0xe823,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData qr_code_icon = UIconData(0xe824,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData remove_friend_icon = UIconData(0xe825,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData remove_icon = UIconData(0xe826,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData right_arrow_inline_button = UIconData(0xe827,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData save_button = UIconData(0xe828,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData search_icon = UIconData(0xe829,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData setting_icon = UIconData(0xe82a,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData settings_logout_icon = UIconData(0xe82b,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData swap_camera_icon = UIconData(0xe82c,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData tap_select_box = UIconData(0xe82d,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData unmute_icon = UIconData(0xe82e,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData vector_stroke = UIconData(0xe82f,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
  static const UIconData video_call_button = UIconData(0xe830,
      uFontFamily: _kIconsFontFamily, uFontPackage: _kIconsFontPackage);
}
