name: 'Comment artifacts'
on:
  push:
    branches:
      - dev
jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "Find your attachments below: "
