
name: Comment artifacts

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    
jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "Find your attachments below: "
